apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.10.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2022.Q2
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:f58678f03a250dbb296ebeb112c9150340155799ba4dad9e90bf347b9ed0ca7b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:61e5a8c1e46f1c18648e0406e2a57c52f911979079020cc57c7a4b06a56940bb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0b2126cfb6054fdf428c1f43b69e36e93a09a49ce15350e9273c98cc08c6598b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:e03945756d86bd189e8c33027fa668d2065c168510085dfd06defd9f40d3e0ab
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_791
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:4e09ee3bd8ff3479fdd00e221b7b1505ae04ca6c64fd6bc9e2f1a34b8e98d137
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_792
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:45a5e054546a2c1ee338518f8477f728f5f7108c9dd8b516b4c79d4a7d6f5ba7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_793
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b74d03ed852a3731467ffda95266ce49f2065972f1c37bf254f3d52b34c11991
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_794
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:ba21779c29b431a22c824e91820705c9501fb0b7d6f7e1ae22fcd3becc8c8a2f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7100
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b575d6eebf44dc9049445e357488efb17a690953852419b534df30e0105b9ca4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7101
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:592b6349141f94efbc3f79e96dfb0152cdaeb16e096c4839b051ad40e135c4d3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0d857b95084e39c011651be89482d4dcc77c2d1c3ac3c6a819f3c9d5a57a425f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:67ae74e72927557c55611d0248347b2099b117ac1aa245dac05856fe782fb59c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:c5f4c08e068b9721967cf7c7cbd9a9e93fb5e39b264dd13b653e99d8f3fa9e0e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:5d39f26f06769fe5c989ea0e0ee8f9166120e152ce2c9bc3336fc8d7cab2ff92
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_791
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:6e9e0e3fddc44fbf87591d8904176407f1ec409d578a7d108c13cdd48d85131b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_792
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3219f90789690a3c5cfcc86e5f602c443e75f1fdb3a19660f43ee3996bfa8f62
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_793
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:979b59325aa0f34eb05625201beba53fccbb83bd5eb80a89dcb5261ae358138f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_794
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ae79b5dab78c4f48993fd8999b09bdcaa918b8e30a9f750bf24d411710f71928
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7100
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3c00b524722b500ff0922fe7a8722868557512183a8f69248f37a68c45c6a770
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7101
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:2b547200f6947069352835339143824195c37a2e8e684310adb7071d872613b8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:dcbff6dca27505445ad7e860e21fe27940768250b6f5dea3bfe0f39a4a270a1d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:dcbff6dca27505445ad7e860e21fe27940768250b6f5dea3bfe0f39a4a270a1d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:dcbff6dca27505445ad7e860e21fe27940768250b6f5dea3bfe0f39a4a270a1d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_791_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_792_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_793_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_794_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:aa7af7e038a12b5202108b362c8af243954603e84034a16c0192684c86d5d28b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7100_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b575d6eebf44dc9049445e357488efb17a690953852419b534df30e0105b9ca4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7101_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:592b6349141f94efbc3f79e96dfb0152cdaeb16e096c4839b051ad40e135c4d3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:c75173b74dbb6a42878b4ba1b20271cacbddf027baacf5b3ab80cbfbf80ec73b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:c75173b74dbb6a42878b4ba1b20271cacbddf027baacf5b3ab80cbfbf80ec73b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:c75173b74dbb6a42878b4ba1b20271cacbddf027baacf5b3ab80cbfbf80ec73b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_791_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_792_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_793_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_794_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:7abfdcfd7b2d3d12b9234f7b057bd199bceefa47bdf02f62236f82a13fdbf5b7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7100_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3c00b524722b500ff0922fe7a8722868557512183a8f69248f37a68c45c6a770
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7101_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:2b547200f6947069352835339143824195c37a2e8e684310adb7071d872613b8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:dcbff6dca27505445ad7e860e21fe27940768250b6f5dea3bfe0f39a4a270a1d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:dcbff6dca27505445ad7e860e21fe27940768250b6f5dea3bfe0f39a4a270a1d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:dcbff6dca27505445ad7e860e21fe27940768250b6f5dea3bfe0f39a4a270a1d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_791_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_792_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_793_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:d4a9176f49ffd9db6051fbda15d47a1aa32c282fb5010d0caf5b9243e80bf055
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_794_s390x
          value: registry.redhat.io/amq7/amq-broker-init-openjdk-11-rhel8@sha256:aa7af7e038a12b5202108b362c8af243954603e84034a16c0192684c86d5d28b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7100_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b575d6eebf44dc9049445e357488efb17a690953852419b534df30e0105b9ca4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7101_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:592b6349141f94efbc3f79e96dfb0152cdaeb16e096c4839b051ad40e135c4d3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:c75173b74dbb6a42878b4ba1b20271cacbddf027baacf5b3ab80cbfbf80ec73b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:c75173b74dbb6a42878b4ba1b20271cacbddf027baacf5b3ab80cbfbf80ec73b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:c75173b74dbb6a42878b4ba1b20271cacbddf027baacf5b3ab80cbfbf80ec73b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_791_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_792_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_793_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:967d840b831b310abd3a468a8652d1fa48b2ce28b342bfab53999245deb004f1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_794_s390x
          value: registry.redhat.io/amq7/amq-broker-openjdk-11-rhel8@sha256:7abfdcfd7b2d3d12b9234f7b057bd199bceefa47bdf02f62236f82a13fdbf5b7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7100_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:3c00b524722b500ff0922fe7a8722868557512183a8f69248f37a68c45c6a770
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7101_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:2b547200f6947069352835339143824195c37a2e8e684310adb7071d872613b8
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:76e218d8347d7d17f1b8875aa919426ca1deafaa5812ae71cda98b535d8d95c1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: amq-broker-operator
      terminationGracePeriodSeconds: 10
