name: CI

env:
  IMAGE_NAME: activemq-artemis-operator
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  OPM_VERSION: v1.54.0
  OPERATOR_SDK_VERSION: v1.28.0
  YQ_VERSION: v4.46.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
    inputs:
      skipTests:
        description: 'Skip Tests'
        required: false
        default: false
        type: boolean
      skipDOTests:
        description: 'Skip DO Tests'
        required: false
        default: false
        type: boolean
      skipTutorials:
        description: 'Skip Tutorials'
        required: false
        default: false
        type: boolean
      skipCatalog:
        description: 'Skip Catalog'
        required: false
        default: false
        type: boolean

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
          cache: true

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
        with:
          cpus: 2
          memory: 4g
          addons: ingress

      - name: Enable minikube ingress-nginx ssl-passthrough
        run: >
          minikube kubectl -- patch deployment -n ingress-nginx ingress-nginx-controller --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value":"--enable-ssl-passthrough"}]'

      - name: Check go.mod and go.sum files
        run: go mod tidy && git status && git diff-index --quiet HEAD --

      - name: Check generate files
        run: make build && make generate-deploy && make bundle && git status && git diff-index --quiet HEAD --

      - name: Build the image
        run: |
          podman build --build-arg TARGETOS=linux --build-arg TARGETARCH=amd64 --label quay.expires-after=90d --label git-sha=$GITHUB_SHA --no-cache --platform linux/amd64 --manifest $IMAGE_NAME:dev.latest .

      - name: Push the image into minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker image list
          podman save --output activemq-artemis-operator-image.tar --format docker-archive $IMAGE_NAME:dev.latest
          docker image load --input activemq-artemis-operator-image.tar
          docker image list

      - name: Execute tests
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipTests }}
        run: IMG="localhost/$IMAGE_NAME:dev.latest" make test-mk-v

      - name: Execute do tests
        if: ${{ github.event_name != 'workflow_dispatch' || !inputs.skipDOTests }}
        run: IMG="localhost/$IMAGE_NAME:dev.latest" make test-mk-do-v

      - name: Run scorecard tests
        run: make scorecard | tee scorecard.log && ! grep 'Suggestions' scorecard.log

      - name: Run the tutorials
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipTutorials }}
        run: minikube delete && minikube start && go run test/utils/tutorials/tester.go

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Checkout arkmq-org.github.io
        uses: actions/checkout@v4
        with:
          repository: arkmq-org/arkmq-org.github.io
          path: arkmq-org.github.io

      - name: Build the docs
        run: >
          rm -rf arkmq-org.github.io/docs &&
          cp -r docs arkmq-org.github.io &&
          rm -rf arkmq-org.github.io/examples &&
          cp -r examples arkmq-org.github.io &&
          cd arkmq-org.github.io &&
          npm install && npm run build

      - name: Set up QEMU
        if: ${{ github.event_name == 'push' }}
        uses: docker/setup-qemu-action@v3

      - name: Build the image for arm64
        if: ${{ github.event_name == 'push' }}
        run: |
          podman build --build-arg TARGETOS=linux --build-arg TARGETARCH=arm64 --label quay.expires-after=90d --label git-sha=$GITHUB_SHA --no-cache --platform linux/arm64 --manifest $IMAGE_NAME:dev.latest .

      - name: Push the dev image
        if: ${{ github.event_name == 'push' }}
        run: |
          COMMIT_TAG=dev.$(date +%Y%m%d).$(git rev-parse --short "$GITHUB_SHA")
          podman login --username=${{ secrets.QUAY_USERNAME }} --password=${{ secrets.QUAY_PASSWORD }} quay.io
          podman manifest push $IMAGE_NAME:dev.latest docker://quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:$COMMIT_TAG
          podman manifest push $IMAGE_NAME:dev.latest docker://quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME:dev.latest

      - name: Build the bundle image
        run: podman build --file bundle.Dockerfile --label quay.expires-after=90d --label git-sha=$GITHUB_SHA --tag $IMAGE_NAME-bundle:dev.latest .

      - name: Push the bundle image
        if: ${{ github.event_name == 'push' }}
        run: |
          COMMIT_TAG=dev.$(date +%Y%m%d).$(git rev-parse --short "$GITHUB_SHA")
          podman login --username=${{ secrets.QUAY_USERNAME }} --password=${{ secrets.QUAY_PASSWORD }} quay.io
          podman tag $IMAGE_NAME-bundle:dev.latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:$COMMIT_TAG
          podman push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:$COMMIT_TAG
          podman tag $IMAGE_NAME-bundle:dev.latest quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:dev.latest
          podman push quay.io/${{ secrets.QUAY_NAMESPACE }}/$IMAGE_NAME-bundle:dev.latest
      
      - name: Install Prerequisites for Catalog Image Creation (opm,yq,operato-sdk)
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipCatalog }}
        run: |
          mkdir -p bin

          echo "Installing opm..."
          curl -sSLo ./bin/opm https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm
          chmod +x ./bin/opm
       
          echo "Installing yq..."
          curl -sSLo ./bin/yq https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
          chmod +x ./bin/yq
      
          echo "Installing operator-sdk..."
          curl -sSLo ./bin/operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/${OPERATOR_SDK_VERSION}/operator-sdk_linux_amd64
          chmod +x ./bin/operator-sdk
        

      - name: Generate and validate catalog
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipCatalog }}
        run: make catalog-generate
        
      - name: Build and push catalog image to Minikube
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipCatalog }}
        run: |
          podman build --file catalog.Dockerfile --label quay.expires-after=90d --label git-sha=$GITHUB_SHA --tag $IMAGE_NAME-catalog:dev.latest .

          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker image list
          podman save --output activemq-artemis-operator-catalog.tar --format docker-archive $IMAGE_NAME-catalog:dev.latest
          docker image load --input activemq-artemis-operator-catalog.tar
          docker image list
     
      - name: Install olm and verify pod readiness
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipCatalog }}
        run: |
          ./bin/operator-sdk olm install

           echo "Waiting for OLM pods to be ready..."
           minikube kubectl -- wait pod -l app=catalog-operator --for=condition=Ready --namespace=olm --timeout=2m
           minikube kubectl -- wait pod -l app=olm-operator --for=condition=Ready --namespace=olm --timeout=2m

      - name: Create and verify CatalogSource
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipCatalog }}
        run: |
          minikube kubectl -- create -f ./examples/catalog/catalog-source.yaml
          sleep 60
          minikube kubectl -- wait pod -l olm.catalogSource=activemq-artemis-operator-source --for=condition=Ready --namespace=operators --timeout=2m

      - name: Create and verify subscription
        # if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' && !inputs.skipCatalog }}
        run: |
          minikube kubectl -- create -f ./examples/catalog/subscription.yaml
          sleep 60
          minikube kubectl -- wait pod -l name=activemq-artemis-operator --for=condition=Ready --namespace=operators --timeout=2m
          